/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "rpc_db.hpp"
#include <iostream>
#include <string>
using namespace std;

bool is_logged = false;

void
rpc_db_prog_1(char *host)
{
	CLIENT *clnt;

	LoginCredentials  *result_1;
	char * login_1_arg = (char*)malloc(sizeof(30));
	strcpy(login_1_arg, "radu");


	bool_t  *result_2;
	char * logout_1_arg = (char*)malloc(sizeof(30));
	strcpy(logout_1_arg, "radu");
	// void  *result_3;
	// char *load_1_arg;
	// void  *result_4;
	// char *store_1_arg;
	// void  *result_5;
	// char *add_1_arg;
	// void  *result_6;
	// char *del_1_arg;
	// void  *result_7;
	// char *update_1_arg;
	// void  *result_8;
	// char *read_1_arg;
	// void  *result_9;
	// char *get_stat_1_arg;
	// void  *result_10;
	// char *get_stat_all_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, RPC_DB_PROG, RPC_DB_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = login_1(&login_1_arg, clnt);
	if (result_1->session_key == 0) {
		printf("eroare\n");
		clnt_perror (clnt, "call failed");
	} else {
		cout << "Logged in" << endl;
		is_logged = true;
	}
	


	result_2 = logout_1(&logout_1_arg, clnt);
	if (*result_2 == false) {
		clnt_perror (clnt, "call failed");
	} else {
		cout << "Logged out" << endl;
		is_logged = false;
	}


	// result_3 = load_1((void*)&load_1_arg, clnt);
	// if (result_3 == (void *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	// }
	// result_4 = store_1((void*)&store_1_arg, clnt);
	// if (result_4 == (void *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	// }
	// result_5 = add_1((void*)&add_1_arg, clnt);
	// if (result_5 == (void *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	// }
	// result_6 = del_1((void*)&del_1_arg, clnt);
	// if (result_6 == (void *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	// }
	// result_7 = update_1((void*)&update_1_arg, clnt);
	// if (result_7 == (void *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	// }
	// result_8 = read_1((void*)&read_1_arg, clnt);
	// if (result_8 == (void *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	// }
	// result_9 = get_stat_1((void*)&get_stat_1_arg, clnt);
	// if (result_9 == (void *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	// }
	// result_10 = get_stat_all_1((void*)&get_stat_all_1_arg, clnt);
	// if (result_10 == (void *) NULL) {
	// 	clnt_perror (clnt, "call failed");
	//}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


// int
// main (int argc, char *argv[])
// {
// 	char *host;

// 	if (argc < 2) {
// 		printf ("usage: %s server_host\n", argv[0]);
// 		exit (1);
// 	}
// 	host = argv[1];
// 	rpc_db_prog_1 (host);
// exit (0);
// }

#define LOGIN_CMD "login"
#define LOGOUT_CMD "logout"

int main (int argc, char *argv[]) 
{
	CLIENT *clnt;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}

#ifndef	DEBUG
	clnt = clnt_create (argv[1], RPC_DB_PROG, RPC_DB_VER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (argv[1]);
		exit (1);
	}
#endif	/* DEBUG */

	string input_command;

	LoginCredentials  *login_result;
	char * login_arg = (char*)malloc(sizeof(30));

	while (true)
	{
		getline(std::cin, input_command);
		
		if (input_command.find(LOGIN_CMD) != string::npos) {

			
			

			// Get username from login command
			string username = input_command.substr(input_command.find(" ") + 1, input_command.length() - 1);
			
			//Check for correct command
			if (username.empty() || (input_command.find(" ") == string::npos)) {
				cout << "Invalid username" << endl;
				continue;
			}

			strcpy(login_arg, username.c_str());

			if (is_logged == true) {
				cout << "Already logged" << endl;
				continue;
			} else {

				login_result = login_1(&login_arg, clnt);
				if (login_result->session_key == 0) {
					clnt_perror (clnt, "call failed");
				} else {
					cout << "Logged in: " << login_result->username << endl;
					is_logged = true;
				}

			}
		} else if (input_command == LOGOUT_CMD) {
			if (is_logged == false) {
				cout << "You are not logged in" << endl;
				continue;
			}
			bool_t  *logout_result;
			logout_result = logout_1(&(login_result->username), clnt);
			if (*logout_result == false) {
				clnt_perror (clnt, "call failed");
			} else {
				cout << "Logged out" << endl;
				is_logged = false;
			}

			
		}
	}
	



#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}
