/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _RPC_DB_H_RPCGEN
#define _RPC_DB_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct SensorData {
	int dataId;
	int noValues;
	float *values;
};
typedef struct SensorData SensorData;

struct LoginCredentials {
	char *username;
	u_long session_key;
};
typedef struct LoginCredentials LoginCredentials;

#define RPC_DB_PROG 0xCAFEBABE
#define RPC_DB_VER 1

#if defined(__STDC__) || defined(__cplusplus)
#define LOGIN 1
extern  LoginCredentials * login_1(char **, CLIENT *);
extern  LoginCredentials * login_1_svc(char **, struct svc_req *);
#define LOGOUT 2
extern  bool_t * logout_1(char **, CLIENT *);
extern  bool_t * logout_1_svc(char **, struct svc_req *);
#define LOAD 3
extern  void * load_1(void *, CLIENT *);
extern  void * load_1_svc(void *, struct svc_req *);
#define STORE 4
extern  void * store_1(void *, CLIENT *);
extern  void * store_1_svc(void *, struct svc_req *);
#define ADD 5
extern  void * add_1(void *, CLIENT *);
extern  void * add_1_svc(void *, struct svc_req *);
#define DEL 6
extern  void * del_1(void *, CLIENT *);
extern  void * del_1_svc(void *, struct svc_req *);
#define UPDATE 7
extern  void * update_1(void *, CLIENT *);
extern  void * update_1_svc(void *, struct svc_req *);
#define READ 8
extern  void * read_1(void *, CLIENT *);
extern  void * read_1_svc(void *, struct svc_req *);
#define GET_STAT 9
extern  void * get_stat_1(void *, CLIENT *);
extern  void * get_stat_1_svc(void *, struct svc_req *);
#define GET_STAT_ALL 10
extern  void * get_stat_all_1(void *, CLIENT *);
extern  void * get_stat_all_1_svc(void *, struct svc_req *);
extern int rpc_db_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LOGIN 1
extern  LoginCredentials * login_1();
extern  LoginCredentials * login_1_svc();
#define LOGOUT 2
extern  bool_t * logout_1();
extern  bool_t * logout_1_svc();
#define LOAD 3
extern  void * load_1();
extern  void * load_1_svc();
#define STORE 4
extern  void * store_1();
extern  void * store_1_svc();
#define ADD 5
extern  void * add_1();
extern  void * add_1_svc();
#define DEL 6
extern  void * del_1();
extern  void * del_1_svc();
#define UPDATE 7
extern  void * update_1();
extern  void * update_1_svc();
#define READ 8
extern  void * read_1();
extern  void * read_1_svc();
#define GET_STAT 9
extern  void * get_stat_1();
extern  void * get_stat_1_svc();
#define GET_STAT_ALL 10
extern  void * get_stat_all_1();
extern  void * get_stat_all_1_svc();
extern int rpc_db_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_SensorData (XDR *, SensorData*);
extern  bool_t xdr_LoginCredentials (XDR *, LoginCredentials*);

#else /* K&R C */
extern bool_t xdr_SensorData ();
extern bool_t xdr_LoginCredentials ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_RPC_DB_H_RPCGEN */
